Revert of Add new, unused methods to SpdyFramerVisitorInterface. (patchset #1 id:1 of https://codereview.chromium.org/1413683005/ )
Reason for revert:
This CL broke the tree:
https://build.chromium.org/p/chromium/builders/Linux/builds/68259/steps/compile/logs/stdio

FAILED: /b/build/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -Wl,-z,now -Wl,-z,relro -Wl,--fatal-warnings -Wl,-z,defs -pthread -Wl,-z,noexecstack -fPIC -B/b/build/slave/Linux/build/src/third_party/binutils/Linux_x64/Release/bin -Wl,--disable-new-dtags -m32 -Wl,-O1 -Wl,--as-needed -Wl,--gc-sections -o flip_in_mem_edsm_server -Wl,--start-group obj/net/tools/flip_server/flip_in_mem_edsm_server.flip_in_mem_edsm_server.o obj/base/libbase.a obj/net/libflip_in_mem_edsm_server_base.a obj/net/libnet.a obj/base/libbase_static.a obj/base/allocator/liballocator_extension_thunks.a obj/third_party/modp_b64/libmodp_b64.a obj/base/third_party/dynamic_annotations/libdynamic_annotations.a obj/base/libsymbolize.a obj/base/libxdg_mime.a obj/third_party/libevent/libevent.a obj/third_party/boringssl/libboringssl.a obj/net/libbalsa.a obj/base/libbase_i18n.a obj/third_party/icu/libicui18n.a obj/third_party/icu/libicuuc.a obj/third_party/protobuf/libprotobuf_lite.a obj/url/liburl_lib.a obj/net/libnet_quic_proto.a obj/base/libbase_prefs.a obj/crypto/libcrcrypto.a obj/sdch/libsdch.a obj/third_party/zlib/libchrome_zlib.a obj/third_party/zlib/libzlib_x86_simd.a obj/build/linux/libgio.a obj/net/libepoll_server.a -Wl,--end-group  -lrt -ldl -lgmodule-2.0 -lgobject-2.0 -lgthread-2.0 -lglib-2.0 -lnss3 -lnssutil3 -lsmime3 -lplds4 -lplc4 -lnspr4 -lgconf-2 -lgio-2.0 -lresolv
obj/net/libflip_in_mem_edsm_server_base.a(obj/net/tools/flip_server/flip_in_mem_edsm_server_base.spdy_interface.o):../../net/tools/flip_server/spdy_interface.cc:vtable for net::SpdySM: error: undefined reference to 'net::SpdySM::OnHeaderFrameStart(unsigned int)'
obj/net/libflip_in_mem_edsm_server_base.a(obj/net/tools/flip_server/flip_in_mem_edsm_server_base.spdy_interface.o):../../net/tools/flip_server/spdy_interface.cc:vtable for net::SpdySM: error: undefined reference to 'net::SpdySM::OnHeaderFrameEnd(unsigned int, bool)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

Original issue's description:
> Add new, unused methods to SpdyFramerVisitorInterface.
>
> The new methods will allow SpdyFramer to pass headers to visitors through a
> SpdyHeadersHandlerInterface.
>
> There are so many descendants of SpdyFramerVisitorInterface that I thought it
> was best to start with the interface change, and add an unused stub
> implementation everywhere.
>
> This CL lands server change 106411694 by birenroy.
>
> BUG=488484
>
> Committed: https://crrev.com/5d0c7230e6d1e8da9597c5a967a7b92638a58442
> Cr-Commit-Position: refs/heads/master@{#357084}

TBR=rch@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=488484

Review URL: https://codereview.chromium.org/1422623009

Cr-Commit-Position: refs/heads/master@{#357093}